
language: cpp
compiler: gcc
dist: bionic

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - pip install --user cpp-coveralls

script:
    - mkdir build
    - cd build
    - cmake -DBUILD_BOOST=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON ../.
    - make -j
    - make test

after_success:
    - coveralls --help
    - coveralls --root .. -E ".*gtest.*" -E ".*CMakeFiles.*" -E ".*third_party.*" -E ".*/test/.*" -E ".*/profile/.*" -E ".*/exercises/.*" -E ".*/messenger/.*"
