
language: cpp

compiler:
    - gcc-5
    - g++-5

addons:
    apt:
        sources:
             - ubuntu-toolchain-r-test
        packages: libboost-all-dev cmake g++-5

script:
    - mkdir build
    - cd build
    - cmake ../.
    - make
    - ./test/test_projeul

