
language: cpp
compiler: gcc
dist: trusty

before_install:
    # C++14
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - pip install --user cpp-coveralls

install:
    # C++14
    - sudo apt-get install -qq g++-5 cmake
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
    - mkdir build
    - cd build
    - cmake -DBUILD_BOOST=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON ../.
    - make -j
    - make test

after_success:
    - coveralls --help
    - coveralls --root .. -E ".*gtest.*" -E ".*CMakeFiles.*" -E ".*third_party.*" -E ".*/test/.*" -E ".*/profile/.*" -E ".*/exercises/.*" -E ".*/messenger/.*"
