/*
 * pe44.cpp
 *
 *  Created on: 13 Jun 2015
 *      Author: evilquinn
 */

#include "pe44.hpp"
#include <iostream>
#include <cmath>
#include <map>
#include <set>
#include <boost/foreach.hpp>
#include "utils.hpp"
#include <stdio.h>
#include <ctype.h>


std::string& pe44::name()
{
    return name_;
}

void pe44::run()
{
    /*
     * Pentagonal numbers are generated by the formula, P(n) = n(3n−1)/2.
     * The first ten pentagonal numbers are:
     *
     *     1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
     *
     * It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their
     * difference, 70 − 22 = 48, is not pentagonal.
     *
     * Find the pair of pentagonal numbers, P(j) and P(k), for which their sum
     * and difference are pentagonal and D = |P(k) − P(j)| is minimised;
     * what is the value of D?
     *
     */

    size_t result = (size_t)-1;

    for(size_t j = 0; j < 1000; ++j)
    {
        for(size_t k = j + 1; k < 1000; ++k)
        {
            //bool diff = true;
            //bool sum = true;
            size_t pent_j = pents_.get_term(j);
            size_t pent_k = pents_.get_term(k);

            size_t pents_diff = pent_k - pent_j;
            if ( ! pents_.is_pentagonal(pents_diff) )
            {
                //diff = false;
                continue;
            }
            size_t pents_sum = pent_j + pent_k;
            if ( ! pents_.is_pentagonal(pents_sum) )
            {
                //sum = false;
                continue;
            }
//            std::cout << "P(" << j << ")=" << pent_j
//                      << ", and P(" << k << ")=" << pent_k
//                      << ", sum: " << pents_sum << "(" << sum
//                      << "), diff: " << pents_diff << "(" << diff << ")"
//                      << std::endl;

            if ( pents_diff < result )
            {
                result = pents_diff;
            }
        }
    }

    std::cout << "PE44 " << result << std::endl;
}
