/*
 * pe45.cpp
 *
 *  Created on: 13 Jun 2015
 *      Author: evilquinn
 */

#include "pe45.hpp"
#include <boost/foreach.hpp>
#include <cctype>
#include <cmath>
#include <cstdio>
#include <iostream>
#include <map>
#include <set>
#include "utils.hpp"

std::string& pe45::name() { return name_; }
void pe45::run()
{
    /*
     * Triangle, pentagonal, and hexagonal numbers are generated by the
     * following formulae:
     * Triangle         Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
     * Pentagonal       Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
     * Hexagonal        Hn=n(2n−1)          1, 6, 15, 28, 45, ...
     *
     * It can be verified that T285 = P165 = H143 = 40755.
     *
     * Find the next triangle number that is also pentagonal and hexagonal.
     *
     *
     */

    pentagonal_numbers pents( PE45_NUM_PENTS );
    triangle_numbers tris( PE45_NUM_TRIS );
    hexagonal_numbers hexs( PE45_NUM_HEXS );
    size_t result = 0;

    for ( size_t tris_pos = 286; tris_pos <= PE45_NUM_TRIS; ++tris_pos )
    {
        if ( pents.is_pentagonal( tris.get_term( tris_pos ) ) &&
             hexs.is_hexagonal( tris.get_term( tris_pos ) ) )
        {
            result = tris.get_term( tris_pos );
        }
    }

    std::cout << name() << " " << result << std::endl;
}
